<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lol</name>
   <tag></tag>
   <elementGuidId>8134d6bc-11e5-4591-ae5d-4d06e72a87fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>empty</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
